// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © R. Karlsen <rk@cassettian.space>

//@version=4
study("BTC in NOK via USD and EUR (favour for USD)")

btcusd = security("BITSTAMP:BTCUSD", "1", close)
usdnok = security("OANDA:USDNOK", "1", close)
btceur = security("COINBASE:BTCEUR", "1", close)
eurnok = security("OANDA:EURNOK", "1", close)

btcusdnok = btcusd * usdnok
btceurnok = btceur * eurnok
favour = btceurnok - btcusdnok

palette = favour >= 0.0 ? color.green : color.red

plot(btcusdnok, title="USD")
plot(btceurnok, title="EUR")
plot(favour, title="Favour", color=palette)


