// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © R. Karlsen <rk@cassettian.space>

//@version=4
study("BTCNOK", scale=scale.right, overlay=true)


cur = input(title="Currency", defval="EUR", options=["USD", "EUR"])

btcsym = if cur == "USD"
    "BITSTAMP:BTCUSD"
else if cur == "EUR"
    "COINBASE:BTCEUR"

noksym = if cur == "USD"
    "OANDA:USDNOK"
else if cur == "EUR"
    "OANDA:EURNOK"

btc = security(btcsym, "1", close)
nok = security(noksym, "1", close)
btcnok = btc * nok

plot(btcnok, color=#FFFFFF00, trackprice=true)
